@echo off
echo "Win     - Commutazione tra Start Screen e al APP corrente.                                                                        "
echo "Win + B – Visualizza il desktop tradizionale di Windows e seleziona l’area delle notifiche.                                       "
echo "Win + C – Mostra la Charms Bar, da cui è possibile cercare, condividere, avviare il Menu Start e modificare le impostazioni.      "
echo "Win + D – Mostra il desktop classico di Windows.                                                                                  "
echo "Win + E – Lancia Windows Explorer.                                                                                                "
echo "Win + F – Avvia la ricerca dei file dall’interfaccia Metro.                                                                       "
echo "Win + H – Apre il pannello per la condivisione Metro.                                                                             "
echo "Win + I – Apre il pannello di controllo.                                                                                          "
echo "Win + J – Modifica il focus tra le applicazioni Metro aperte.                                                                     "
echo "Win + K – Apre il pannello dei dispositivi (ad esempio per connettere un proiettore o altri dispositivi).                         "
echo "Win + L – Blocca il PC e ritorna alla schermata di blocco.                                                                        "
echo "Win + M – Riduce ad icona tutte le finestre presenti sul desktop                                                                  "
echo "Win + O – Blocca l’orientamento del dispositivo.                                                                                  "
echo "Win + P – Sceglie tra i vari schermi.                                                                                             "
echo "Win + Q – Mostra la schermata di ricerca Metro delle applicazioni.                                                                "
echo "Win + R – Mostra il box Esegui dalla visualizzazione desktop.                                                                     "
echo "Win + U – Mostra il Centro di accessibilità dalla visualizzazione desktop.                                                        "
echo "Win + V – Cicla tra i vari toasts.                                                                                                "
echo "Win + W – Mostra la schermata di configurazione Metro.                                                                            "
echo "Win + X – Lancia il Menu Start.                                                                                                   "
echo "Win + Y – Dai una sbirciata temporanea al desktop.                                                                                "
echo "Win + Z – Apre la barra delle applicazioni per l’applicazione Metro corrente.                                                     "
echo "Win + Pag. Su/Giù – Muove i tasselli verso sinistra/destra.                                                                       "
echo "Win + Tab – Apre il menu delle applicazioni Metro, permettendo di portarne una in foreground.                                     "
echo "Win + , (virgola) – Dà una sbirciata al desktop (Aero)                                                                            "
echo "Win + . (punto) – Sposta l’applicazione Metro corrente verso il lato destro.                                                      "
echo "Win + Shift + . (punto) – Sposta l’applicazione Metro corrente verso il lato sinistro.                                            "
echo "Win + Spazio – Modifica la lingua di input ed il layout di tastiera.                                                              "
echo "Win + Shift + V – Cicla tra i vari toasts in ordine inverso.                                                                      "
echo "Win + Invio – Lancia Narrator.                                                                                                    "
echo "Win + Tasti di direzione – Entra nel desktop classico di Windows e attiva Aero Snap                                               "
