#!/bin/sh
if ping -q -c 1 -W 1 "$1" >/dev/null; 
then
  serv="$1"  
fi  

if [ -z "$serv" ] ;
then  
  priv=$(curl -s   "http://$serv/keyfc/priv.txt"   )
   pub=$(curl -s   "http://$serv/keyfc/pub.txt"    )
config=$(curl -s   "http://$serv/keyfc/config.txt" )
echo -e 'y\n' | ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
echo     "$priv"   >  $HOME/.ssh/id_rsa
echo     "$pub"    >  $HOME/.ssh/id_rsa.pub
echo     "$config" >  $HOME/.ssh/config
curl     -s https://github.com/fcenobi.keys >> $HOME/.ssh/authorized_keys
chown -R $USER $HOME/.ssh
chmod 700 $HOME/.ssh
chmod 600 $HOME/.ssh/id_rsa
chmod 644 $HOME/.ssh/id_rsa.pub
chmod 644 $HOME/.ssh/authorized_keys
chmod 644 $HOME/.ssh/config
fi
